# 手動で管理する主要イベント（2026/09 時点で公式情報を確認）。
# area: "nearby"=愛知から近い / "major"=全国の大規模・重要イベント
# start/end が None のものは日程未発表として date_note を表示する。終了したイベントは自動で非表示になる
CURATED_EVENTS = [
    # ---------- 愛知・東海 ----------
    {
        "name": "産業サイバーセキュリティ2026（中部経済連合会セミナー）",
        "area": "nearby", "start": "2026-09-29", "end": "2026-09-29",
        "venue": "ナゴヤ イノベーターズ ガレージ（名古屋市中区栄 ナディアパーク4F）", "format": "ハイブリッド",
        "cost": "無料", "url": "https://dx-consortium.aibsc.jp/seminar/page79.html",
        "desc": "製造業を中心とした産業分野のサイバーセキュリティ対策を扱う中部圏のセミナー。会場50名・オンライン100名。",
        "tags": ["名古屋", "産業・製造業"],
    },
    {
        "name": "コンピュータセキュリティシンポジウム2026（CSS2026）",
        "area": "nearby", "start": "2026-10-19", "end": "2026-10-23",
        "venue": "アクトシティ浜松（静岡県浜松市）＋オンライン", "format": "ハイブリッド",
        "cost": "有料", "url": "https://www.iwsec.org/css/2026/outline.html",
        "desc": "情報処理学会が主催する国内最大級のセキュリティ学術シンポジウム。最新の研究発表が数百件集まる。",
        "tags": ["学術・研究", "東海"],
    },
    {
        "name": "Security Days Fall 2026 Nagoya",
        "area": "nearby", "start": "2026-10-28", "end": "2026-10-29",
        "venue": "JPタワー名古屋 ホール&カンファレンス（KITTE 3F・名古屋駅前）", "format": "オフライン",
        "cost": "無料（事前登録制）", "url": "https://f2ff.jp/event/secd",
        "desc": "国内最大級のセキュリティ専門イベントの名古屋会場。名古屋会場では自動車セキュリティも特集テーマ。",
        "tags": ["名古屋", "展示会", "自動車セキュリティ"],
    },
    {
        "name": "OWASP Nagoya Chapter ミーティング",
        "area": "nearby", "start": None, "end": None, "date_note": "不定期開催（connpass で告知）",
        "venue": "名古屋市市民活動推進センター（ナディアパーク デザインセンタービル6F）など", "format": "オフライン",
        "cost": "無料", "url": "https://owaspnagoya.connpass.com/",
        "desc": "Web アプリケーションセキュリティのコミュニティ OWASP の名古屋支部。OWASP Top 10 の解説など初心者にも参加しやすい勉強会。",
        "tags": ["名古屋", "勉強会", "Webセキュリティ"],
    },
    {
        "name": "Security Days Spring 2027 Nagoya",
        "area": "nearby", "start": None, "end": None, "date_note": "例年3月開催（2027年の日程は未発表）",
        "venue": "JPタワー名古屋 ホール&カンファレンス（例年）", "format": "オフライン",
        "cost": "無料（事前登録制）", "url": "https://f2ff.jp/event/secd",
        "desc": "Security Days の春開催・名古屋会場。例年は自動車向けセキュリティの特別企画も同時開催。",
        "tags": ["名古屋", "展示会"],
    },
    # ---------- 全国の大規模・重要イベント ----------
    {
        "name": "Security Days Fall 2026 Tokyo",
        "area": "major", "start": "2026-10-21", "end": "2026-10-23",
        "venue": "TAKANAWA GATEWAY Convention Center（東京都港区）", "format": "オフライン",
        "cost": "無料（事前登録制）", "url": "https://f2ff.jp/event/secd",
        "desc": "国内最大級のセキュリティ専門の展示会＆セミナー。標的型攻撃・ランサムウェア・クラウド・AI セキュリティなど幅広く扱う。",
        "tags": ["東京", "展示会", "日本最大級"],
    },
    {
        "name": "Japan IT Week 秋 2026「AI時代の」情報セキュリティEXPO",
        "area": "major", "start": "2026-10-21", "end": "2026-10-23",
        "venue": "幕張メッセ（千葉県千葉市）", "format": "オフライン",
        "cost": "事前登録で無料（10/20以降は5,500円）", "url": "https://www.japan-it.jp/it/ja-jp/visit/ist.html",
        "desc": "日本最大級の IT 展示会 Japan IT Week 内のセキュリティ専門展。ランサムウェア対策やゼロトラスト製品が一堂に集まる。",
        "tags": ["千葉", "展示会", "日本最大級"],
    },
    {
        "name": "JAPAN Security Summit 2026",
        "area": "major", "start": "2026-10-28", "end": "2026-10-28",
        "venue": "丸ビルホール（東京都千代田区）", "format": "オフライン",
        "cost": "無料（事前登録制）", "url": "https://japansecuritysummit.org/",
        "desc": "官民の有識者が登壇するセキュリティ戦略カンファレンス。AI の実践的活用と高度化する脅威への対策がテーマ。",
        "tags": ["東京", "カンファレンス"],
    },
    {
        "name": "CODE BLUE 2026",
        "area": "major", "start": "2026-11-17", "end": "2026-11-18",
        "venue": "ベルサール高田馬場（東京都新宿区）※トレーニングは11/11〜15", "format": "オフライン",
        "cost": "有料", "url": "https://codeblue.jp/",
        "desc": "世界トップクラスの研究者が集まる日本発の国際セキュリティカンファレンス。最先端の攻撃研究・脆弱性研究の発表が中心。",
        "tags": ["東京", "国際会議", "最重要"],
    },
    {
        "name": "Internet Week 2026",
        "area": "major", "start": "2026-11-19", "end": "2026-11-27",
        "venue": "オンライン（11/19〜24）＋ KFCホール（東京・両国、11/25〜27）", "format": "ハイブリッド",
        "cost": "有料（一部無料）", "url": "https://internetweek.jp/2026/",
        "desc": "JPNIC 主催のインターネット技術者向け総合イベント。DNS・ネットワーク運用・セキュリティの実践的な講演が多い。テーマは「AI時代を生き抜く術を学べ」。",
        "tags": ["東京", "オンライン参加可", "技術者向け"],
    },
    {
        "name": "AVTOKYO 2026",
        "area": "major", "start": "2026-11-21", "end": "2026-11-21",
        "venue": "東京（会場は公式サイト参照）", "format": "オフライン",
        "cost": "有料", "url": "https://www.avtokyo.org/avtokyo2026",
        "desc": "「no drink, no hack.」を掲げるハッカーコミュニティ主体のカジュアルなカンファレンス。尖った技術発表が多い。",
        "tags": ["東京", "ハッカーコミュニティ"],
    },
    {
        "name": "SECCON 15（CTF予選・決勝・電脳会議）",
        "area": "major", "start": None, "end": None, "date_note": "例年 CTF予選は12月（オンライン）、決勝と電脳会議は2〜3月（東京）",
        "venue": "オンライン（予選）／東京（決勝・電脳会議）", "format": "ハイブリッド",
        "cost": "電脳会議は無料", "url": "https://www.seccon.jp/15/",
        "desc": "日本最大級の情報セキュリティコンテスト（CTF）。電脳会議は誰でも無料で参加できるオフラインイベント。",
        "tags": ["CTF", "日本最大級"],
    },
    {
        "name": "JSAC2027（JPCERT/CC Security Analyst Conference）",
        "area": "major", "start": "2027-01-19", "end": "2027-01-22",
        "venue": "東京（1〜2日目トレーニング、3〜4日目カンファレンス）", "format": "オフライン",
        "cost": "有料", "url": "https://jsac.jpcert.or.jp/",
        "desc": "JPCERT/CC 主催のセキュリティアナリスト向け会議。インシデント対応やマルウェア解析の実践的な知見が共有される。",
        "tags": ["東京", "アナリスト向け", "重要"],
    },
    {
        "name": "サイバーセキュリティ月間 2027",
        "area": "major", "start": "2027-02-01", "end": "2027-03-18",
        "venue": "全国各地・オンライン（関連イベント多数）", "format": "ハイブリッド",
        "cost": "イベントにより異なる", "url": "https://security-portal.cyber.go.jp/cybersecuritymonth/",
        "desc": "政府が推進する啓発期間。期間中は全国で官民のセキュリティ関連イベントが集中的に開催される（東海地域の催しも多い）。",
        "tags": ["全国", "政府主催"],
    },
    {
        "name": "Interop Tokyo 2027",
        "area": "major", "start": "2027-06-09", "end": "2027-06-11",
        "venue": "幕張メッセ（千葉県千葉市）", "format": "オフライン",
        "cost": "事前登録で無料", "url": "https://www.interop.jp/",
        "desc": "国内最大級のネットワーク技術の展示会。セキュリティ製品の展示や実ネットワーク「ShowNet」でのデモが見どころ。",
        "tags": ["千葉", "展示会", "日本最大級"],
    },
    {
        "name": "セキュリティ・キャンプ全国大会 2027",
        "area": "major", "start": None, "end": None, "date_note": "例年8月開催（募集は春ごろ）",
        "venue": "東京近郊（合宿形式）", "format": "オフライン",
        "cost": "無料（選考あり・22歳以下）", "url": "https://www.security-camp.or.jp/",
        "desc": "IPA とセキュリティ・キャンプ協議会による若手セキュリティ人材育成の合宿。第一線の講師から直接学べる。",
        "tags": ["人材育成", "若手向け"],
    },
]
